### ISSUE TITLE
Go small or go home - The Raspberry Pi Zero Dramble

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-dramble#73]
![cef1nhfw8aamxx7](https://cloud.githubusercontent.com/assets/481677/14062190/bc58719a-f363-11e5-85c8-b8c756a1891d.jpg)

I'm doing some more experimental work this weekend after finally acquiring a few Pi Zeros from Micro Center... I'd like to now do a full netinstall or zero-config install of Raspbian/Lite, with networking preconfigured.

Currently, I do the following for the Pi Zero:

  1. Flash Raspbian Lite to a microSD card (on Mac):
    1. `diskutil unmountDisk /dev/disk2`
    2. `pv 2016-02-26-raspbian-jessie-lite.img | sudo dd of=/dev/rdisk2 bs=1m`
  2. Boot up Ubuntu VM (in VMware Fusion), mount 'boot' volume to it.
  3. `sudo nano /media/[uuid-of-drive]/etc/wpa_supplicant/wpa_supplicant.conf`
  4. Add in my SSID info to the bottom of the file:

    ```
    network={
      ssid="MyNetwork"
      psk="MyPassword"
    }
    ```

  5. `sudo nano /media/[uuid-of-drive]/etc/modprobe.d/8192cu.conf`

    ```
    options 8192cu rtw_power_mgnt=0 rtw_enusbss=0
    ```

  6. Unmount the microSD card, stick it in the Pi Zero, and we're ready to go!

The Zero doesn't have a LAN jack or a 2nd USB port, so it's annoying having to dongle up a bunch of cables just to type in a few commands to initialize the connection. Thus, automate all the things!

## TODO

  - [x] <s>Automate the provisioning. Maybe [use preseed/netinstall](https://github.com/debian-pi/raspbian-ua-netinst), maybe [modify NOOBS](http://raspberrypi.stackexchange.com/a/31594/6506), maybe [hack `cmdline.txt`](https://www.raspberrypi.org/forums/viewtopic.php?p=497748&sid=f6993041d449af429ceca8323c3b7e99#p497748), maybe figure out a quick way to update without having to use an Ubuntu VM to mount the ext4 partition...</s> (SEE: #75).
    - Automate the wpa_supplicant.conf WiFi configuration.
    - Automate the 8192cu power management.
    - Automate adding my SSH key to the pi user account.
  - [x] Update guides on Wiki to show how to do things with Raspberry Pi Zero instead of Pi 2/3. (See [old notes about B+ from Drupal Pi](https://github.com/geerlingguy/drupal-pi/commit/a3d59841174fc4f1775de100821d16783ca5ef64) which should apply here).
  - [x] Figure out optimal settings for extremely limited Raspberry Pi Zero resources.

**Comment by geerlingguy** [comment]
(Somewhat) surprisingly, everything _just worked_; had to make a couple changes to make wireless USB adapters work correctly (`wlan0`) with the networking setup, and also had to change the following vars in `config.yml` for the smaller RAM allotment on the Zero:

```
mysql_innodb_buffer_pool_size: "256M" # For 512MB RAM.
mysql_myisam_sort_buffer_size: "32M" # For 512MB RAM.
```

I'll make sure to document these changes either in the Wiki, the README, or in both places.

**Comment by geerlingguy** [comment]
Apparently I've run into [this](https://www.drupal.org/node/2627446#comment-10963303) again; the networking setup I added in the 2nd commit above shows the static IP I set if I run `ifconfig` on the Pi itself, but requests to other Pis are showing the old DHCP addresses the Pis got from the router...

```
# On db1:
$ ifconfig -a
wlan0     Link encap:Ethernet  HWaddr f4:f2:6d:12:95:80  
          inet addr:10.0.1.63  Bcast:10.0.1.255  Mask:255.255.255.0

# Sending a request from db1 to www1:
Mar 28 02:44:35 www1 kernel: [104944.736413] Dropped by firewall: IN=wlan0 OUT= MAC=f4:f2:6d:12:98:7c:f4:f2:6d:12:95:80:08:00 SRC=10.0.1.46 DST=10.0.1.50 LEN=60 TOS=0x10 PREC=0x00 TTL=64 ID=3852 DF PROTO=TCP SPT=42452 DPT=3306 WINDOW=29200 RES=0x00 SYN URGP=0
```

**Comment by geerlingguy** [comment]
On the balancer:

```
$ ip addr
2: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether f4:f2:6d:19:18:64 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.60/24 brd 10.0.1.255 scope global wlan0
       valid_lft forever preferred_lft forever
    inet 10.0.1.49/24 brd 10.0.1.255 scope global secondary wlan0
       valid_lft forever preferred_lft forever
    inet6 fe80::f6f2:6dff:fe19:1864/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by geerlingguy** [comment]
Looks like I just needed to configure dhcpd, like I did for `eth0`. Simple enough; commit with fix to follow.

**Comment by geerlingguy** [comment]
This is fixed. The Zero is pretty slow :)

http://www.pidramble.com/wiki/benchmarks/drupal (see the Zero section).
